DATASET:
  root_dataset: "./data/"
  list_train: "./data/outside15k_train.odgt"
  list_val: "./data/outside15k_val_small.odgt"
  list_stats: "./data/outside15k_all.odgt"
  num_class: 24
  imgSizes: (300, 400, 500, 600, 700, 800)
  imgMaxSize: 1100
  padding_constant: 32
  segm_downsampling_rate: 8
  random_flip: True
  random_crop: False
  classInfo: "./data/outside15k.json"

MODEL:
  arch_encoder: "resnet50dilated"
  arch_decoder: "ppm_deepsup"
  fc_dim: 2048

TRAIN:
  batch_size_per_gpu: 2
  num_epoch: 20
  start_epoch: 0
  epoch_iters: 5000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 1
  disp_iter: 20

VAL:
  visualize: False
  checkpoint: "epoch_20.pth"

TEST:
  checkpoint: "epoch_20.pth"
  result: "./"

DIR: "ckpt/outside15k-resnet50dilated-ppm_deepsup"
