DATASET:
  root_dataset: "./data/"
  list_train: "./data/outside15k_train.odgt"
  list_val: "./data/example_image_list.odgt"
  list_stats: "./data/outside15k_val.odgt"
  num_class: 24
  imgSizes: (300, 400, 500, 600, 700, 800)
  imgMaxSize: 1100
  padding_constant: 32
  segm_downsampling_rate: 4
  random_flip: True
  random_crop: True
  classInfo: "./data/outside15k.json"
  
MODEL:
  arch_encoder: "resnet50"
  arch_decoder: "upernet"
  fc_dim: 2048
#  weights_encoder: "./ckpt/ade20k-hrnetv2-ocr_2/encoder_epoch_30.pth"
#  weights_encoder: "./ckpt/ade20k-hrnetv2-ocr_2/decoder_epoch_30.pth"
  spatial_mask: False

TRAIN:
  batch_size_per_gpu: 2
  start_epoch: 35
  num_epoch: 100
  epoch_iters: 10000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 1
  disp_iter: 50
  eval: False

VAL:
  checkpoint: "epoch_598.pth"
  visualize: True

TEST:
  checkpoint: "epoch_60.pth"
  result: "./test_dataset/"

DIR: "weights/outside15k-resnet50-outsideNet/"
